export const QUERY_KEY = {
    TODO: {
        GET_TODO: "GET_TODO",
        GET_TODO_STATUS_COUNT: "GET_TODO_STATUS_COUNT",
        CREATE_TODO: "CREATE_TODO",
        UPDATE_TODO: "UPDATE_TODO",
    },
    TIMELINE: {
        GET_TIMELINE: "GET_TIMELINE",
    },
    PROJECT: {
        GET_PROJECTS: "GET_PROJECTS",
        GET_PROJECT: "GET_PROJECT",
        CREATE_PROJECT: "CREATE_PROJECT",
        UPDATE_PROJECT: "UPDATE_PROJECT",
        DELETE_PROJECT: "DELETE_PROJECT",
    },
    USER: {
        GET_MY_INFO: "GET_MY_INFO",
        UPDATE_MY_INFO: "UPDATE_MY_INFO",
        CHANGE_PASSWORD: "CHANGE_PASSWORD"
    },
}